[tox]
envlist =
    py{35,36,37,38,39,310}-django22
    py{36,37,38,39,310}-django30
    py{36,37,38,39,310}-django31
    py{36,37,38,39,310}-django32
    py{38,39,310}-django40
    py{38,39,310}-django41
    py{310}-djangoupstream
    py{310}-drfupstream
    black

[gh-actions]
python =
    3.4: py34
    3.5: py35
    3.6: py36
    3.7: py37
    3.8: py38
    3.9: py39
    3.10: py310

[testenv]
deps =
    django22: Django~=2.2.17
    django30: Django>=3.0,<3.1
    django31: Django>=3.1,<3.2
    django32: Django>=3.2,<4.0
    django40: Django>=4.0,<4.1
    django41: Django>=4.1,<4.2
    djangoupstream: https://github.com/django/django/archive/main.tar.gz

    drfupstream: Django~=3.2.0
    drfupstream: https://github.com/encode/django-rest-framework/archive/master.tar.gz
    django22: djangorestframework~=3.12.0
    django30,django31,django32: djangorestframework~=3.12.0
    django40: djangorestframework~=3.13.0
    django41: djangorestframework~=3.13.0
    djangoupstream: https://github.com/encode/django-rest-framework/archive/master.tar.gz
    coverage
commands =
    coverage run {envbindir}/django-admin test --pythonpath=. --settings=tests.settings {posargs}

[testenv:black]
basepython = python3
skip_install = true
deps =
    black>=19.10b0
commands =
    black --check --diff ordered_model/ tests/ setup.py


[flake8]
max-line-length = 100
