# Generated by Django 3.0.6 on 2020-05-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedMutex',
            fields=[
                ('key', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
